# Generated by Django 2.2.1 on 2019-06-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190608_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs1',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
